In [1]:
import numpy as np

In [ ]:
a.sum()  #ผลรวม
a.prod() #ผลคูณ
a.mean() #ค่าเฉลี่ย
a.max()  #ค่าสูงสุด
a.min()  #ค่าต่ำสุด
a.argmax() #ระบุตำแหน่งที่มากที่สุด
a.argmin() #ระบุตำแหน่งที่ตำแหน่งต่ำที่สุด
#np.min(b,axis = 0) หาค่าตำสุด     0 แนวตั้ง 1แนวนอน
#np.mix(b,axis = 0) หาค่าสูงสุด     0 แนวตั้ง 1แนวนอน
#c = a.dot(b) คูณเมททริก.product   ขนาดต้องเท่ากัน

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) # 1 ชั้น
a   

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
b = np.array([[1,2,3],[4,5,6]]) # 2 ชั้น
b   

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3 ชั้น
c 

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [39]:
c[:] #เอาทุกสมาชิก (ทั้งอาเรย์)   
c[2:] # เริ่มจาก index 2 (รวม) ไปจนสุด → [2 3 4 5 6 7 8 9]    
c[:5] #เริ่มที่ 0 จนถึง ก่อน index 5 → indices 0..4 → [0 1 2 3 4]
c[3:7] #เลือกจะเอาช่วงไหน  ระบุช่วง indices 3..6 → [3 4 5 6]
c[3:7:2] #กะโดดข้ามสมาชิก เพิ่มทีละ 2 (กะโดดทีละ 2) → [3 5]
c[1:,1:] #เอา แถวตั้งแต่ index 1 ลงไป และ คอลัมน์ตั้งแต่ index 1 ลงไป
c[:2,2:] #เอา แถวตั้งแต่เริ่มจนก่อน index 2 (คือแถว 0 และ 1) และ คอลัมน์ตั้งแต่ index 2 ถึงสุด

array([[[7, 8, 9]]])

In [46]:
b[[0,1],[2,0]] # ระบุสมาชิก ใน array

array([3, 4])

In [7]:
c.ndim # เช็คชั้นของ 

3

In [32]:
c.shape #บอกรูปร่าง โครงสร้าง มิติ มองเป็นแถวก่อน 

array([[[1, 2, 3],
        [4, 5, 6]]])

In [33]:
c.size #บอกจำนวนสมาชิก มีกี่ตัว

6

In [34]:
c.itemsize # บอกขนาด array  บอก byte โดยคำนวณ bit  หา byte

8

In [10]:
A = np.zeros([5,5],dtype = "int") #สร้างเมททริก ให้เป็น 0 ทั้งหมด เมททริกจตุรัสด้านต้องเท่ากัน เมททริกขนาด 2 มิติ
A

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
B = np.ones([5,5]) #สร้างเมททริก ให้เป็น 1 ทั้งหมดแบบ 2 มิติ
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
C = np.ones(10) # แบบ 1มิติ
C

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
D = np.full(6,10) # ขนาดของ array ที่ต้องการสร้าง 6 และ 10 คือ ค่าที่ต้องการเติมให้ทุกตำแหน่
D

array([10, 10, 10, 10, 10, 10])

In [17]:
E = np.full([5,10],7) #แบบ 2 มิติ
E

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [18]:
F = np.empty([3,4]) # สร้างarrayเปล่า นำขนาดมาใช้เช่น 3*4,4*4 คิดเฉพาะโครงสร้างไม่คิดข้อมูลสุ่มตัวเลขขึ้นมาในarray
F

array([[1.69716213e-316, 0.00000000e+000, 1.01855798e-312,
        9.54898106e-313],
       [1.06099790e-312, 1.01855798e-312, 1.23075756e-312,
        1.20953760e-312],
       [1.08221785e-312, 9.76118064e-313, 1.14587773e-312,
        1.90979621e-312]])

In [20]:
G = np.identity(5,dtype = "int") # สร้าง array แนวทแยงมุม เป็น 1
G

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [21]:
H = np.eye(3,4) #ทะแยงมุม เป็น 1 ที่เหลือเป็น 0 เปลี่ยนมุมได้ 
H

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [25]:
I = np.linspace(1,5) #  สร้างarray 1 มิติ กำหนดช่วงจุดเริ่มต้นและจุดสุดท้าย
I
# I = np.linspace(1,5,4) เหมาะกับการมาพอตราฟ เพราะเว้นช่วงเท่าเท่ากัน
# I = np.linspace(1,5,endpoint=False) ไม่เอาตัวสุดท้าย  กำหนดช่วงข้อมูล

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [26]:
J = np.arange(1,10,2) # 1 จุดเริ่มต้น ,10 จุดสิ้นสุด,เพิ่มค่าขึ้นที่ละ 2,กำหนดช่วงเริ่มต้น และจุดสิ้นสุด
J

array([1, 3, 5, 7, 9])

In [27]:
K = np.random.random([2,2]) #สุ่มข้อมูลสมาชิก  0 ถึงก่อน 1
K

array([[0.14269579, 0.95259891],
       [0.88792596, 0.8164285 ]])

In [48]:
L = np.arange(1,10) # สร้าง array 1 -9
L

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
c.reshape #คืนค่า (return) array ใหม่ ที่เปลี่ยนโครงสร้าง (shape) ข้อมูลดิบ (data buffer) ยังเหมือนเดิม
c.resize  #เปลี่ยนแปลงโครงสร้างถาวร//เปลี่ยน array เดิมโดยตรง (in-place) และอาจตัด/เติมค่า

<function ndarray.reshape>

In [53]:
c.flatten() # จัดรูปแบบรูปร่าง จาก 2 มิติให้เป็น 1 มิติ  ไม่ถาวร ส่งค่ากลับมาในarrayก้อนใหม่

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
c = a.ravel() # แปลง array ให้เป็น 1D (flat)
c

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1])

In [57]:
b.transpose()  # transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [66]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])
c = np.concatenate((a,b), axis=1) #รวมร่าง 2 ตัว array หรือ เอา a กับ b มาต่อกันตามแกนที่กำหนด (default = axis=0)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [68]:
a = np.append(a,100) # นำสมาชิกก้อนใหม่มาต่อท้าย คือ 100 
a

array([  1,   2,   3,   4, 100, 100])

In [72]:
f = np.append(b,[[10],[20]],axis=1)  # นำสมาชิกก้อนใหม่มาต่อท้าย 2มิติ

f

array([[ 5,  6, 10, 10],
       [ 7,  8, 20, 20]])

In [73]:
d = np.insert(a,1,100) # แทรกสมาชิก แทรกข้อมูลลงไป แทรกลง index 1 ,ขนาด 1มิติ
d

array([  1, 100,   2,   3,   4, 100, 100])

In [75]:
e = np.insert(a,(1,3),100) # แทรกหลายตัว,ขนาด 1มิติ
e    
# np.insert(a,1,100,axis=0)  2มิติ แนวตั้ง
# np.insert(a,1,100,axis=1)  2มิติ แนวนอน

array([  5, 100,   6,  10, 100,   7,   8,  20])

In [77]:
a = np.delete(a,1) #ลบสมาชิก ขนาด  1 มิติ
a

array([  1,   4, 100, 100])

In [78]:
q = np.arange(1,13).reshape(4,3) #สร้าง array 2 มิติ ขนาด (4,3)ค่าข้างในเรียงจาก 1 → 12 
q

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# axis=0 → ลบ แถว
# axis=1 → ลบ คอลัมน์
# np.delete(a,2,axis=0) # ลบแถวหรือคอลัมน์ในอาร์เรย์ array ขนาด 2 มิติ
# np.split(a,4)  # แยกข้อมูล ออกเป็นส่วนที่สมาชิกเท่ากัน 4 ส่วน  แต่ละกลุ่มเท่ากัน หรือกลุ่ม ละ 4 ขนาด 1 มิติ //แบ่งอาร์เรย์ออกเป็น ส่วนเท่ากัน จำนวน 4 ส่วนใช้ได้กับ 1D หรือ 2D แต่ต้องแน่ใจว่า จำนวนสมาชิกหารด้วย 4 ลงตัว
# np.hsplit(a,4) # 2มิติ  แนวตั้ง  แยกข้อมูล ออกเป็นส่วนที่สมาชิกเท่ากัน 4 หรือแบ่งกลุ่ม
# np.vsplit(a,4) # 2มิติ  แนวนอน   แยกข้อมูล ออกเป็นส่วนที่สมาชิกเท่ากัน 4 หรือแบ่งกลุ่ม